[project]
name = "pwgen"
description = "A random password generator in your toolset."
version = "1.0.0"
authors = [
  {name = "Muhammad Altaaf", email = "taafuuu@gmail.com"}
]


[project.scripts]
pwgen = "pwgen.main:main"

