[project]
name = "passwd-gen"
description = "A random password generator in your toolset."
version = "2.0.0"
readme = "README.md"
license = {file = "LICENSE"}
authors = [
  {name = "Muhammad Altaaf", email = "taafuuu@gmail.com"}
]


[project.scripts]
passwd-gen = "passwd_gen.main:main"

