[project]
name = "pwgen"
description = "A random password generator in your toolset."
version = "1.1.0"
readme = "README.md"
license = {file = "LICENSE"}
authors = [
  {name = "Muhammad Altaaf", email = "taafuuu@gmail.com"}
]


[project.scripts]
pwgen = "pwgen.main:main"

